name = "louvainjewellery"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "catalogue-db"
database_id = "f81b376050c04d6a9c6b4d5e6e6ed4a7"

# R2 Storage Configuration
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "jewellery-images"