name = "louvainjewellery"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "catalogue-db"
database_id = "14e71bf1-235a-4c08-9138-b64722a4d280"